[package]
name = "rsynth"
version = "0.1.0"
authors = ["Johan Burell <johan.burell@gmail.com>"]
edition = "2018"

[dependencies]
synth = "0.11.0"
portaudio = "0.7.0"
pitch_calc = "0.11.0"
sample = "0.6.0"
rsynth-data-import = { path="../rsynth-data-import" }